# Generated by Django 5.2.8 on 2025-12-08 09:49

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, null=True)),
                ('activation_code', models.CharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('meister', django.db.models.manager.Manager()),
            ],
        ),
    ]
