# Generated by Django 5.2.8 on 2025-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='new_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
