# Generated by Django 5.2.8 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
