# Generated by Django 5.2.8 on 2025-12-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email_alter_user_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
