# Generated by Django 5.2.8 on 2025-11-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(choices=[('Taiwan', 'Tw'), ('Laos', 'La'), ('Norway', 'No'), ('Kyrgyzstan', 'Kg'), ('Austria', 'At'), ('China', 'Ch')], default='Norway')),
            ],
        ),
    ]
