# Generated by Django 5.2.8 on 2025-12-08 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_created_at_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 8, 9, 49, 17, 301930, tzinfo=datetime.timezone.utc)),
        ),
    ]
